apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  labels:
    elasticsearch-master-http-client: "true"
    elasticsearch-master-transport-client: "true"
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.94.0
  ports:
    - name: promexporter
      port: 8889
      protocol: TCP
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors: {}
    exporters:
      logging: 
        loglevel: debug
      zipkin:
           endpoint: "http://zipkin.default.svc:9411/api/v2/spans"
           format: proto
      elasticsearch/log:
           endpoints: "https://elasticsearch-master.default.svc:9200"
           logs_index: my_logs_index
           user: elastic
           password: mukund@12
           tls:
              insecure_skip_verify: true
      prometheus:
           endpoint: "0.0.0.0:8889"
           namespace: prometheus
           const_labels:
              label1: value1
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, zipkin]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]
        logs:
          receivers: [otlp]
          exporters: [logging,elasticsearch/log]
