extensions:
  health_check:
  pprof:
    endpoint: 127.0.0.1:1777
  zpages:
    endpoint: 127.0.0.1:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  syslog:
    tcp:
      listen_address: 127.0.0.1:54527
    protocol: rfc3164
    location: UTC
    operators:
    - type: move
      from: attributes.message
      to: body

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./data/syslogfile_3164  
    append: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]  # Only using debug for now

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]  # Only using debug for now

    logs:
      receivers: [syslog]
      processors: [batch]
      exporters: [debug,file]  # Debug and file exporter

  extensions: [health_check, pprof, zpages]
